services:
  nginx:
    image: nginx:stable-alpine
    volumes:
    - ./wordpress:/var/www/html
    - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    networks:
    - wp-network
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
    - "3306:3306"
    networks:
    - wp-network

  php:
    build: 
      context: ./Dockerfile
      dockerfile: php-fpm.dockerfile
    ports:
    - "9000:9000"
    volumes:
    - ./wordpress:/var/www/html
    networks:
    - wp-network

  # wp-cli:
  #   image: wordpress:cli
  #   volumes:
  #   - ./wordpress:/var/www/html

  # phpmyadmin:
  #   image: phpmyadmin
  #   restart: always
  #   ports:
  #     - 8080:80
  #   environment:
  #     - PMA_ARBITRARY=1
networks:
  wp-network:
    driver: bridge
